name: راهنمای برنامه نویسی
description: استانداردهای لازم برای ایجاد کدهای HTML و CSS سازگار ، انعطاف پذیر و پایدار
url: https://codeguide.arash-hatami.ir
permalink: pretty
sass:
  style: compressed

plugins:
  - jekyll-include-cache

exclude:
  [
    .jekyll-cache,
    README.md,
    Gemfile,
    Gemfile.lock,
    _site,
    CNAME,
    LICENSE.md,
    .idea,
    vendor,
  ]
version: 4.0.0
og_image: https://raw.githubusercontent.com/mdo/code-guide/gh-pages/code-guide-social.png
